import { randomUUID } from "node:crypto";
import {
    DEFAULT_JOURNAL_ARCHIVED,
    DEFAULT_JOURNAL_FAVORITE,
    DEFAULT_JOURNAL_PINNED,
    DEFAULT_JOURNAL_TAGS,
    JOURNAL_SCHEMA_VERSION,
} from "../constants";
import { journalRepository } from "../repository";
import type { JournalEntry } from "../types";

/**
 * User-supplied input for creating a journal entry. Every other
 * JournalFrontMatter field (id, schema version, timestamps, tags,
 * favorite/pinned/archived) is generated by JournalService.createJournal()
 * itself — the caller never supplies them.
 */
export interface CreateJournalInput {
    title: string;
    journalDate: string;
}

/**
 * Application-level use cases for working with journal entries.
 *
 * This is the only layer Server Actions are permitted to call directly
 * — Server Actions must never import the Journal Repository
 * themselves. JournalService knows nothing about React, Next.js, the
 * filesystem, Markdown, or paths; it only composes the Journal
 * Repository.
 *
 * Beyond createJournal()'s automatic-value generation, every method
 * here delegates straight through to the repository, unchanged. That
 * is deliberate: the purpose of this layer is to establish a stable
 * boundary between Server Actions and the Repository, so that future
 * orchestration — duplicate title handling, slug generation, applying
 * templates, a Git save workflow, attachment processing, analytics —
 * has a proper home without any Server Action ever needing to change.
 */
export interface JournalService {
    /** Lists every journal entry. */
    listJournals(): Promise<JournalEntry[]>;

    /** Returns the journal entry with the given id, or null if none exists. */
    getJournal(id: string): Promise<JournalEntry | null>;

    /**
     * Creates a new journal entry from minimal user input, generating
     * every other front matter field automatically, and returns the
     * entry as persisted.
     */
    createJournal(input: CreateJournalInput): Promise<JournalEntry>;

    /** Overwrites an existing journal entry. Throws if none with that id exists yet. */
    updateJournal(entry: JournalEntry): Promise<void>;

    /** Deletes the journal entry with the given id. Throws if no such entry exists. */
    deleteJournal(id: string): Promise<void>;
}

/**
 * Orders journal entries for display: pinned entries first, then by
 * journal date descending (newest first). journalDate is an ISO
 * "YYYY-MM-DD" string, so lexicographic comparison already matches
 * chronological order.
 *
 * This is a presentation-ordering business rule, not a storage
 * concern — the Repository makes no ordering guarantee, so it lives
 * here rather than in the Repository or in a UI component, where every
 * future consumer of listJournals() would otherwise have to re-derive
 * it.
 */
function compareByPinnedThenJournalDateDescending(a: JournalEntry, b: JournalEntry): number {
    if (a.frontMatter.pinned !== b.frontMatter.pinned) {
        return a.frontMatter.pinned ? -1 : 1;
    }

    return b.frontMatter.journalDate.localeCompare(a.frontMatter.journalDate);
}

/** Builds a brand-new JournalEntry from minimal input, stamping every automatic field. */
function buildNewJournalEntry(input: CreateJournalInput): JournalEntry {
    const now = new Date().toISOString();

    return {
        frontMatter: {
            version: JOURNAL_SCHEMA_VERSION,
            id: randomUUID(),
            title: input.title,
            journalDate: input.journalDate,
            createdAt: now,
            updatedAt: now,
            tags: [...DEFAULT_JOURNAL_TAGS],
            favorite: DEFAULT_JOURNAL_FAVORITE,
            pinned: DEFAULT_JOURNAL_PINNED,
            archived: DEFAULT_JOURNAL_ARCHIVED,
        },
        content: "",
    };
}

export const journalService: JournalService = {
    listJournals: async () => {
        const entries = await journalRepository.listEntries();
        return [...entries].sort(compareByPinnedThenJournalDateDescending);
    },
    getJournal: (id) => journalRepository.getEntry(id),
    createJournal: async (input) => {
        const entry = buildNewJournalEntry(input);
        await journalRepository.createEntry(entry);
        return entry;
    },
    updateJournal: (entry) => journalRepository.updateEntry(entry),
    deleteJournal: (id) => journalRepository.deleteEntry(id),
};
