import { randomUUID } from "node:crypto";
import { applyTemplateVariables } from "@/features/template";
import {
    DEFAULT_JOURNAL_ARCHIVED,
    DEFAULT_JOURNAL_FAVORITE,
    DEFAULT_JOURNAL_PINNED,
    DEFAULT_JOURNAL_TAGS,
    JOURNAL_SCHEMA_VERSION,
} from "../constants";
import { journalRepository } from "../repository";
import type { JournalEntry, JournalFrontMatter } from "../types";

/**
 * User-supplied input for creating a journal entry. Every other
 * JournalFrontMatter field (id, schema version, timestamps, tags,
 * favorite/pinned/archived) is generated by JournalService.createJournal()
 * itself — the caller never supplies them.
 *
 * `content` seeds the entry's initial Markdown body — e.g. a template's
 * content, copied in by the caller before this is invoked. Omitting it
 * (or a Blank template's empty content) starts the entry empty, same
 * as before templates existed.
 */
export interface CreateJournalInput {
    title: string;
    journalDate: string;
    content?: string;
}

/**
 * Search/filter criteria for listJournals(). `query` matches against
 * title, Markdown content, and tags (case-insensitive, partial, and
 * trimmed before matching); an empty/omitted query matches everything.
 * favorite/pinned/archived are "only show entries where this flag is
 * true" toggles — omitting one (or passing `false`) means that
 * dimension isn't filtered at all, not "show only entries where it's
 * false".
 */
export interface JournalSearchFilters {
    query?: string;
    favorite?: boolean;
    pinned?: boolean;
    archived?: boolean;
}

/**
 * Application-level use cases for working with journal entries.
 *
 * This is the only layer Server Actions are permitted to call directly
 * — Server Actions must never import the Journal Repository
 * themselves. JournalService knows nothing about React, Next.js, the
 * filesystem, Markdown, or paths; it composes the Journal Repository
 * plus, for resolving `{{...}}` template variables in createJournal()'s
 * seed content, Template's pure applyTemplateVariables() string
 * substitution utility — never the Template Repository or Service.
 *
 * Beyond createJournal()'s automatic-value generation and
 * listJournals()'s search/filter/sort, every method here delegates
 * straight through to the repository, unchanged. That is deliberate:
 * the purpose of this layer is to establish a stable boundary between
 * Server Actions and the Repository, so that future orchestration —
 * duplicate title handling, slug generation, applying templates, a Git
 * save workflow, attachment processing, analytics — has a proper home
 * without any Server Action ever needing to change.
 */
export interface JournalService {
    /**
     * Lists journal entries, optionally narrowed by search/filter
     * criteria, always ordered pinned-first then by journal date
     * descending. Omitting `filters` (or passing an empty object)
     * returns every entry.
     */
    listJournals(filters?: JournalSearchFilters): Promise<JournalEntry[]>;

    /** Returns the journal entry with the given id, or null if none exists. */
    getJournal(id: string): Promise<JournalEntry | null>;

    /**
     * Creates a new journal entry from minimal user input, generating
     * every other front matter field automatically, and returns the
     * entry as persisted.
     */
    createJournal(input: CreateJournalInput): Promise<JournalEntry>;

    /** Overwrites an existing journal entry. Throws if none with that id exists yet. */
    updateJournal(entry: JournalEntry): Promise<void>;

    /** Deletes the journal entry with the given id. Throws if no such entry exists. */
    deleteJournal(id: string): Promise<void>;
}

/**
 * Orders journal entries for display: pinned entries first, then by
 * journal date descending (newest first). journalDate is an ISO
 * "YYYY-MM-DD" string, so lexicographic comparison already matches
 * chronological order.
 *
 * This is a presentation-ordering business rule, not a storage
 * concern — the Repository makes no ordering guarantee, so it lives
 * here rather than in the Repository or in a UI component, where every
 * future consumer of listJournals() would otherwise have to re-derive
 * it.
 */
function compareByPinnedThenJournalDateDescending(a: JournalEntry, b: JournalEntry): number {
    if (a.frontMatter.pinned !== b.frontMatter.pinned) {
        return a.frontMatter.pinned ? -1 : 1;
    }

    return b.frontMatter.journalDate.localeCompare(a.frontMatter.journalDate);
}

/** Trims and lowercases a raw search query for case-insensitive, partial matching. */
function normalizeSearchQuery(query: string | undefined): string {
    return (query ?? "").trim().toLowerCase();
}

/**
 * Whether an entry's title, content, or tags contain the normalized
 * query as a substring (case-insensitive, partial match). An empty
 * query matches every entry.
 */
function matchesQuery(entry: JournalEntry, normalizedQuery: string): boolean {
    if (normalizedQuery.length === 0) {
        return true;
    }

    const titleMatches = entry.frontMatter.title.toLowerCase().includes(normalizedQuery);
    const contentMatches = entry.content.toLowerCase().includes(normalizedQuery);
    const tagMatches = entry.frontMatter.tags.some((tag) => tag.toLowerCase().includes(normalizedQuery));

    return titleMatches || contentMatches || tagMatches;
}

/**
 * Whether an entry satisfies the favorite/pinned/archived filters.
 * Each filter is a "must be true" toggle: omitting one (or passing
 * `false`) means that dimension isn't filtered at all.
 */
function matchesFlagFilters(entry: JournalEntry, filters: JournalSearchFilters): boolean {
    if (filters.favorite && !entry.frontMatter.favorite) {
        return false;
    }
    if (filters.pinned && !entry.frontMatter.pinned) {
        return false;
    }
    if (filters.archived && !entry.frontMatter.archived) {
        return false;
    }

    return true;
}

/**
 * Derives the `{{year}}`, `{{month}}`, `{{day}}`, and `{{weekday}}`
 * template variables from an ISO "YYYY-MM-DD" journalDate. Parsed and
 * formatted in UTC so the parts always match the literal date string,
 * regardless of the server's local timezone.
 */
function deriveDatePartsFromJournalDate(journalDate: string): {
    year: string;
    month: string;
    day: string;
    weekday: string;
} {
    const [year, month, day] = journalDate.split("-");
    const weekday = new Date(`${journalDate}T00:00:00Z`).toLocaleDateString("en-US", {
        weekday: "long",
        timeZone: "UTC",
    });

    return { year, month, day, weekday };
}

/**
 * Builds the `{{...}}` template variables available when a new journal
 * entry is created from a template: the entry's own front matter
 * fields, plus year/month/day/weekday derived from its journalDate.
 */
function buildTemplateVariables(frontMatter: JournalFrontMatter): Record<string, string> {
    return {
        title: frontMatter.title,
        journalDate: frontMatter.journalDate,
        createdAt: frontMatter.createdAt,
        updatedAt: frontMatter.updatedAt,
        ...deriveDatePartsFromJournalDate(frontMatter.journalDate),
    };
}

/**
 * Builds a brand-new JournalEntry from minimal input, stamping every
 * automatic field, then resolving any `{{...}}` template variables in
 * the seed content against those same generated fields — this is why
 * variable resolution happens here rather than in the Server Action
 * that calls createJournal(): id/createdAt/updatedAt don't exist yet
 * at that point.
 */
function buildNewJournalEntry(input: CreateJournalInput): JournalEntry {
    const now = new Date().toISOString();

    const frontMatter: JournalFrontMatter = {
        version: JOURNAL_SCHEMA_VERSION,
        id: randomUUID(),
        title: input.title,
        journalDate: input.journalDate,
        createdAt: now,
        updatedAt: now,
        tags: [...DEFAULT_JOURNAL_TAGS],
        favorite: DEFAULT_JOURNAL_FAVORITE,
        pinned: DEFAULT_JOURNAL_PINNED,
        archived: DEFAULT_JOURNAL_ARCHIVED,
    };

    return {
        frontMatter,
        content: applyTemplateVariables(input.content ?? "", buildTemplateVariables(frontMatter)),
    };
}

export const journalService: JournalService = {
    listJournals: async (filters = {}) => {
        // journalRepository.listEntries() already reads and parses every
        // file's full content in one pass; filtering here afterward, on
        // the array already in memory, reads each file exactly once —
        // never re-opens a file to check content a second time.
        const entries = await journalRepository.listEntries();
        const normalizedQuery = normalizeSearchQuery(filters.query);

        const filtered = entries.filter(
            (entry) => matchesQuery(entry, normalizedQuery) && matchesFlagFilters(entry, filters)
        );

        return filtered.sort(compareByPinnedThenJournalDateDescending);
    },
    getJournal: (id) => journalRepository.getEntry(id),
    createJournal: async (input) => {
        const entry = buildNewJournalEntry(input);
        await journalRepository.createEntry(entry);
        return entry;
    },
    updateJournal: (entry) => journalRepository.updateEntry(entry),
    deleteJournal: (id) => journalRepository.deleteEntry(id),
};
