"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { assertAuthenticated } from "@/lib/auth";
import { templateService } from "@/features/template";
import { formatOrdinalDate } from "../components/formatJournalDate";
import { JournalValidationError } from "../errors";
import { journalService } from "../services";
import { JOURNAL_LIST_PATH, getJournalDetailPath } from "./paths";

export interface CreateJournalFormErrors {
    journalDate?: string;
    form?: string;
}

export interface CreateJournalFormState {
    errors: CreateJournalFormErrors;
}

function readTrimmedField(formData: FormData, field: string): string {
    const value = formData.get(field);
    return typeof value === "string" ? value.trim() : "";
}

/**
 * Server Action invoked directly by CreateJournalButton (constructing
 * its own FormData with an empty title/templateId and today's date) —
 * there is no longer a form for a user to fill in before this runs;
 * every field defaults sensibly enough that "New Journal" creates and
 * redirects immediately. The `{ errors }`-shaped state/FormData
 * signature is a holdover from when this was bound via
 * useActionState() to a real form; kept as-is since it still works
 * fine as a plain callable action and renaming it is a bigger, purely
 * cosmetic change than this redesign pass needs to make.
 *
 * Validates the user-supplied journal date and surfaces a friendly message
 * for it — every other JournalFrontMatter field is generated by
 * JournalService.createJournal(), not here. Title is optional: a blank
 * title defaults to the journal date written out as an ordinal, e.g.
 * "5th August 2026" (see formatOrdinalDate).
 * Repository/filesystem errors are never shown to the user directly:
 * JournalValidationError (a defensive fallback — the browser's native
 * date input already constrains the format) and any other unexpected
 * failure both collapse to one generic message.
 *
 * On success, revalidates the journal list and redirects to the newly
 * created entry's detail page, using the id returned by
 * JournalService.createJournal() directly — no extra repository lookup
 * needed to find it.
 *
 * If a `templateId` was submitted, that template's Markdown content
 * seeds the new entry's body (looked up via TemplateService, the same
 * boundary JournalService sits behind). An empty, missing, or unknown
 * `templateId` all fall back to an empty body — the same as the Blank
 * template, and the same as before templates existed — rather than
 * failing the whole creation over a template lookup.
 */
export async function createJournal(
    _previousState: CreateJournalFormState,
    formData: FormData
): Promise<CreateJournalFormState> {
    await assertAuthenticated();

    const journalDate = readTrimmedField(formData, "journalDate");
    const templateId = readTrimmedField(formData, "templateId");

    const errors: CreateJournalFormErrors = {};

    if (journalDate.length === 0) {
        errors.journalDate = "Journal date is required.";
    }

    if (Object.keys(errors).length > 0) {
        return { errors };
    }

    const title = readTrimmedField(formData, "title") || formatOrdinalDate(journalDate);

    let createdEntryId: string;

    try {
        const template = templateId.length > 0 ? await templateService.getTemplate(templateId) : null;
        const entry = await journalService.createJournal({ title, journalDate, content: template?.content });
        createdEntryId = entry.frontMatter.id;
    } catch (error) {
        if (error instanceof JournalValidationError) {
            return {
                errors: { form: "That journal date doesn't look valid. Please check it and try again." },
            };
        }

        return {
            errors: { form: "Something went wrong while creating the journal entry. Please try again." },
        };
    }

    revalidatePath(JOURNAL_LIST_PATH);
    redirect(getJournalDetailPath(createdEntryId));
}
